name: app-build-rust

on:
  workflow_call:
    inputs:
      fullSemVer:
        type: string
        description: e.g. 1.2.301-feature-my-feature.12
        required: true

jobs:
  app-build-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: cargo version
        run: cargo version
        if: false #debug

      - name: cargo fmt
        run: cargo fmt --all --check

      - name: cargo clippy
        run: cargo clippy -- -D warnings

      - name: cargo fetch
        run: cargo fetch

      - name: cargo build
        run: cargo build --release

      # - name: cargo test
      #   run: cargo test

      #TODO: could run cargo test here, etc...
