name: ci

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "preview/**"
    paths-ignore:
      - .github/dependabot.yml
      - LICENSE
      - README.md
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  release:
    uses: ./.github/workflows/gha-release-versioning.yml
    with:
      gv-source: action
