name: _dotnet-publish-nuget

on:
  workflow_call:
    inputs:
      configuration:
        type: string
        description: e.g. Debug or Release
        required: true
        default: Release
      execute-tests:
        type: boolean
        description: Execute unit tests?
        required: false
        default: true
      push-preview:
        type: boolean
        description: Push a pre-release NuGet package from a non-default branch?
        required: true
        default: false
      package-filter:
        type: string
        description: Comma-separated package ID prefixes to push e.g. CasCap.Common.Caching
        required: false
        default: ''
    secrets:
      #Note: We don't need to pass in GITHUB_TOKEN to a reusable workflow. When a reusable workflow is triggered by a caller workflow, the github context is always associated with the caller workflow. The called workflow is automatically granted access to github.token and secrets.GITHUB_TOKEN.
      #see https://docs.github.com/en/actions/using-workflows/reusing-workflows
      NUGET_API_KEY:
        description: e.g. secrets.NUGET_API_KEY
        required: false
      SONAR_TOKEN:
        description: e.g. secrets.SONAR_TOKEN
        required: false

jobs:
  versioning:
    uses: f2calv/gha-workflows/.github/workflows/gha-release-versioning.yml@v1
    with:
      tag-prefix: ''
      tag-and-release: false

  build:
    runs-on: ubuntu-latest
    needs: [versioning]
    steps:
      - uses: f2calv/gha-dotnet-nuget@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          configuration: ${{ inputs.configuration }}
          execute-tests: ${{ inputs.execute-tests }}
          push-preview: ${{ inputs.push-preview }}
          package-filter: ${{ inputs.package-filter }}
          version: ${{ needs.versioning.outputs.version }}

  release:
    needs: [versioning, build]
    if: needs.versioning.outputs.release-exists == 'false'
      && (github.ref == format('refs/heads/{0}', github.event.repository.default_branch) || inputs.push-preview == 'true')
    uses: f2calv/gha-workflows/.github/workflows/gha-release-versioning.yml@v1
    permissions:
      contents: write
    with:
      semVer: ${{ needs.versioning.outputs.version }}
      tag-prefix: ''
      move-major-tag: false

  # gha-sonarqube:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - uses: actions/checkout@v7
  #       with:
  #         fetch-depth: 0
  #
  #     - uses: f2calv/gha-sonarqube-dotnet@v2
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         sonar-token: ${{ secrets.SONAR_TOKEN }}
  #         build-configuration: ${{ inputs.configuration }}
