name: ci

on:
  workflow_call:
    inputs:
      BuildConfiguration:
        type: string
        description: Build Configuration
        required: true
        default: Release
      #workflow_call boolean input type is boolean
      #workflow_dispatch boolean input type is treated like string - because it actually has 3 values true/false/'empty'
      PublishPreview:
        type: string #cannot be boolean see https://github.com/actions/runner/issues/1483
        description: Publish preview branch?
        required: true
        default: false

jobs:
  build:
    #no point using matrix build as "Container operations are only supported on Linux runners"
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest,windows-latest]
    # runs-on: ${{matrix.os}}
    runs-on: ubuntu-latest
    outputs:
      # SemVer: ${{ steps.dotnet.outputs.SemVer }}
      # FullSemVer: ${{ steps.dotnet.outputs.FullSemVer }}
      BuildConfiguration: ${{ steps.dotnet.outputs.BuildConfiguration }}
    # env:
    #   PublishPreview: ${{ inputs.PublishPreview }}
    steps:
      - uses: f2calv/gha-dotnet-nuget@main
        id: dotnet
        with:
          BuildConfiguration: ${{ github.event.inputs.BuildConfiguration }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          PublishPreview: ${{ inputs.PublishPreview }}

  SonarQube:
    runs-on: windows-latest
    needs: build
    steps:
      - uses: f2calv/gha-sonarqube@main
        with:
          BuildConfiguration: ${{ needs.build.outputs.BuildConfiguration }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
