name: gha-release-versioning
#Note: Workflow is called by other workflows to a) determine a semantic version, b) tag the repo with this create a semantic version and c) create a release.

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      # GITHUB_TOKEN:
      #   description: e.g. USD{{ secrets.GITHUB_TOKEN }}
      #   required: true
      #   type: string
      #Note: We don't need to pass in GITHUB_TOKEN to a reusable workflow. When a reusable workflow is triggered by a caller workflow, the github context is always associated with the caller workflow. The called workflow is automatically granted access to github.token and secrets.GITHUB_TOKEN.
      #see https://docs.github.com/en/actions/using-workflows/reusing-workflows
      semVer:
        description: Pass in an externally generated semantic version, if empty then uses GitVersion.
        required: false
        type: string
        default: ''
      tag-prefix:
        description: Prefix the semver, e.g. 1.0.1 or v1.0.1
        required: false
        type: string
        default: v
      move-major-tag:
        description: Create and/or move major version tag, e.g. when creating v1.0.2 then move v1 tag up from the v1.0.1 commit.
        required: false
        type: boolean
        default: true
      tag-and-release:
        description: Sets a Git tag and creates a corresponding release.
        required: false
        type: boolean
        default: true
    outputs:
      semVer:
        description: e.g. 1.2.301
        value: ${{ jobs.gha-release-versioning.outputs.semVer }}
      fullSemVer:
        description: e.g. 1.2.301-feature-my-feature.12
        value: ${{ jobs.gha-release-versioning.outputs.fullSemVer }}
      major:
        description: e.g. 1
        value: ${{ jobs.gha-release-versioning.outputs.major }}
      minor:
        description: e.g. 2
        value: ${{ jobs.gha-release-versioning.outputs.minor }}
      patch:
        description: e.g. 301
        value: ${{ jobs.gha-release-versioning.outputs.patch }}

jobs:
  gha-release-versioning:
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gha-release-versioning.outputs.semVer }}
      fullSemVer: ${{ steps.gha-release-versioning.outputs.fullSemVer }}
      major: ${{ steps.gha-release-versioning.outputs.major }}
      minor: ${{ steps.gha-release-versioning.outputs.minor }}
      patch: ${{ steps.gha-release-versioning.outputs.patch }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - #uses: f2calv/gha-release-versioning@v1
        uses: f2calv/gha-release-versioning@f2calv/gitversion-via-docker
        id: gha-release-versioning
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          semVer: ${{ inputs.semVer }}
          tag-prefix: ${{ inputs.tag-prefix }}
          move-major-tag: ${{ inputs.move-major-tag }}
          tag-and-release: ${{ inputs.tag-and-release }}
