name: gha-release-versioning
#Note: Workflow is called by other workflows to a) determine a semantic version, b) tag the repo with this create a semantic version and c) create a release.

on:
  workflow_call:
    inputs:
      tag-prefix:
        description: Prefix the semver, i.e. 1.0.1 or v1.0.1
        required: false
        type: string
        default: v
      move-major-tag:
        description: Create and/or move major version tag, i.e. when creating v1.0.2 then move v1 tag up from the v1.0.1 commit.
        required: false
        type: boolean
        default: true
    #Note: We don't need to pass in GITHUB_TOKEN to a reusable workflow. When a reusable workflow is triggered by a caller workflow, the github context is always associated with the caller workflow. The called workflow is automatically granted access to github.token and secrets.GITHUB_TOKEN.
    #see https://docs.github.com/en/actions/using-workflows/reusing-workflows

jobs:
  gha-release-versioning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: f2calv/gha-release-versioning@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag-prefix: ${{ inputs.tag-prefix }}
          move-major-tag: ${{ inputs.move-major-tag }}
