name: helm-chart-build

on:
  workflow_call:
    inputs:
      registry:
        type: string
        description: e.g. ghcr.io, docker.io, xyz.azurecr.io
        default: ghcr.io
      tag:
        type: string
        description: e.g. latest, latest-dev, 1.2.3
        required: true
      chart-name:
        type: string
        description: If not set uses the name of the current repository

jobs:
  build-chart:
    runs-on: ubuntu-latest
    permissions:
      packages: write #for pushing helm package
    steps:
      - uses: actions/checkout@v4

      - name: set chart-name (1 of 2)
        if: inputs.chart-name == ''
        run: |
          CHART_NAME=$(echo $REPOSITORY | sed "s|$USERNAME\/||g")
          echo "CHART_NAME=charts/$CHART_NAME" >> $GITHUB_ENV

      - name: set chart-name (2 of 2)
        if: inputs.chart-name != ''
        run: echo "CHART_NAME=charts/${{ inputs.chart-name }}" >> $GITHUB_ENV

      - name: set CHART_REPOSITORY
        run: echo "CHART_REPOSITORY=${{ github.repository_owner }}/$CHART_NAME" >> $GITHUB_ENV

      - name: setup helm (1 of 2) #pulls version from devcontainer
        run: |
          npm install --global json5
          json5 -c .devcontainer/devcontainer.json
          VERSION_TO_INSTALL=$(cat .devcontainer/devcontainer.json | jq -r '.features[] | select(.helm | . != null).helm')
          echo "VERSION_TO_INSTALL=$VERSION_TO_INSTALL" >> $GITHUB_ENV
          echo "VERSION_TO_INSTALL=$VERSION_TO_INSTALL"

      - name: setup helm (2 of 2)
        uses: azure/setup-helm@v4
        with:
          version: ${{ env.VERSION_TO_INSTALL }}

      - name: helm registry login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ inputs.registry }}/${{ github.repository_owner }} --username ${{ github.repository_owner }} --password-stdin

      - uses: actions/setup-python@v5
        with:
          python-version: 3.7
        if: false #not implemented/working yet

      - name: chart-testing (setup)
        uses: helm/chart-testing-action@v2
        if: false #not implemented/working yet

      - name: chart-testing (run list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch main)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
        if: false #not implemented/working yet

      - name: chart-testing (run lint)
        run: ct lint
        if: false #not implemented/working yet

      - name: create kind cluster
        uses: helm/kind-action@v1
        #if: steps.list-changed.outputs.changed == 'true'
        if: false #not implemented/working yet

      - name: chart-testing (run install)
        run: ct install
        if: false #not implemented/working yet

      - name: helm package
        run: |
          helm package ${{ github.workspace }}/$CHART_NAME/ --destination ${{ github.workspace }}/artifacts/ --app-version ${{ inputs.tag }}

      - name: helm push
        run: |
          helm push ${{ github.workspace }}/artifacts/$CHART_NAME-${{ inputs.tag }}.tgz oci://ghcr.io/${{ github.repository_owner }}
