name: lint

on:
  workflow_call:
    inputs:
      pre-commit-version:
        description: Set pre-commit version.
        type: string
        default: 3.7.1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      #https://pre-commit.com/
      - name: pre-commit
        run: |
          echo "Install..."
          #sudo apt-get update && sudo apt-get install -y python3 pip pre-commit
          python3 -m pip install 'pre-commit~=${{ inputs.pre-commit-version }}' -q

          #python3 -m pre_commit autoupdate
          #python3 -m pre_commit install --install-hooks
          #python3 -m pre_commit run --all-files --verbose
          python3 -m pre_commit run --verbose
