name: test

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      move-major-tag:
        description: Create and/or move major version tag, i.e. when creating v1.0.2 then move v1 tag up from the v1.0.1 commit.
        required: false
        type: boolean
        default: true
      test-true:
        required: false
        type: boolean
        default: true
      test-false:
        required: false
        type: boolean
        default: true

jobs:
  gha-release-versioning:
    runs-on: ubuntu-latest
    steps:

      - name: test1
        if: github.event.inputs.test-true == true
        run: |
          echo 'hello world'

      - name: test2
        if: github.event.inputs.test-true == 'true'
        run: |
          echo 'hello world'

      #works!
      - name: test3
        if: inputs.test-true == true
        run: |
          echo 'hello world'

      - name: test4
        if: inputs.test-true == 'true'
        run: |
          echo 'hello world'
  
      - name: test5
        if: ${{ github.event.inputs.test-true }}
        run: |
          echo 'hello world'
  
      #works!
      - name: test6
        if: ${{ inputs.test-true }}
        run: |
          echo 'hello world'