name: _test

on:
  workflow_dispatch:
    inputs:
      test-true:
        required: false
        type: boolean
        default: true
      test-false:
        required: false
        type: boolean
        default: true
  workflow_call:
    inputs:
      test-true:
        required: false
        type: boolean
        default: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      #workflow_dispatch fails
      - name: test1
        if: github.event.inputs.test-true == true
        run: |
          echo 'hello world'

      #workflow_dispatch works
      - name: test2
        if: github.event.inputs.test-true == 'true'
        run: |
          echo 'hello world'

      #workflow_dispatch works
      - name: test3
        if: inputs.test-true == true
        run: |
          echo 'hello world'

      #workflow_dispatch fails
      - name: test4
        if: inputs.test-true == 'true'
        run: |
          echo 'hello world'

      #workflow_dispatch works
      - name: test5
        if: ${{ github.event.inputs.test-true }}
        run: |
          echo 'hello world'

      #workflow_dispatch works
      - name: test6
        if: ${{ inputs.test-true }}
        run: |
          echo 'hello world'
